# Numpy - Übung 1 - Lösung

2026-05-03 ug - Version 1.1

In [1]:
import numpy as np

**Aufgabe1:** Erzeuge folgendes 2D NumPy Array

![Bild 1](../bilder/Numpy_Übung_1_Bild_1.png)

erwartetes Ergebnis:
```Python 
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])
```
Verwende `arange()` und `reshape()`
Speichere das Ergebnis in der Variablen `a`.
<br>
Bitte die Anweisung in folgende Zelle eintragen:

In [2]:
# Bitte hier die Lösung eintragen
a = np.arange(30).reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

**Aufgabe2**: Erzeuge folgenden Ausschnitt:

![Bild 2](../bilder/Numpy_Übung_1_Bild_2.png)

Erwartetes Ergebnis:
```Python 
np.int64(7)
```
Bitte die Anweisung in folgende Zelle eintragen:

In [3]:
# Bitte hier die Lösung eintragen
a[1,1]

np.int64(7)

**Aufgabe3**: Erzeuge folgenden Ausschnitt:

![Bild 3](../bilder/Numpy_Übung_1_Bild_3.png)

Erwartetes Ergebnis:
```Python 
array([ 6,  7,  8,  9, 10, 11])
```
Bitte die Anweisung in folgende Zelle eintragen:

In [4]:
# Bitte hier die Lösung eintragen
a[1]

array([ 6,  7,  8,  9, 10, 11])

**Aufgabe4**: Erzeuge folgenden Ausschnitt:

![Bild 4](../bilder/Numpy_Übung_1_Bild_4.png)

Erwartetes Ergebnis:
```Python 
array([ 2,  8, 14, 20, 26])
```
Bitte die Anweisung in folgende Zelle eintragen:

In [5]:
# Bitte hier die Lösung eintragen
a[:,2]

array([ 2,  8, 14, 20, 26])

**Aufgabe5**: Erzeuge folgenden Ausschnitt:

![Bild 5](../bilder/Numpy_Übung_1_Bild_5.png)

Erwartetes Ergebnis:
```Python 
array([[ 2,  5],
       [ 8, 11],
       [14, 17],
       [20, 23],
       [26, 29]])
```
Bitte die Anweisung in folgende Zelle eintragen:

In [6]:
# Bitte hier die Lösung eintragen
a[:,2::3]

array([[ 2,  5],
       [ 8, 11],
       [14, 17],
       [20, 23],
       [26, 29]])

**Aufgabe6**: Erzeuge folgenden Ausschnitt:

![Bild 6](../bilder/Numpy_Übung_1_Bild_6.png)

Erwartetes Ergebnis:
```Python 
array([[ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17]])
```
Bitte die Anweisung in folgende Zelle eintragen:

In [7]:
# Bitte hier die Lösung eintragen
a[1:3,1:]

array([[ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17]])

**Aufgabe7**: Erzeuge folgenden Ausschnitt:

![Bild 7](../bilder/Numpy_Übung_1_Bild_7.png)

Erwartetes Ergebnis:
```Python 
array([13, 14, 15, 16])
```
Bitte die Anweisung in folgende Zelle eintragen:

In [8]:
# Bitte hier die Lösung eintragen
a[2,1:-1]

array([13, 14, 15, 16])

**Aufgabe8**: Erzeuge folgenden Ausschnitt:

![Bild 8](../bilder/Numpy_Übung_1_Bild_8.png)

Erwartetes Ergebnis:
```Python 
array([[ 7,  9],
       [19, 21]])
```
Bitte die Anweisung in folgende Zelle eintragen:

In [9]:
# Bitte hier die Lösung eintragen
a[1::2,1:-2:2]

array([[ 7,  9],
       [19, 21]])