# Numpy - Übersicht-Zugriffsmethoden

2026-05-03 ug V1.2

In [1]:
import numpy as np

### Ein-dimensionales Arrays 

Erzeugen eines ein-dimensionalen Arrays 

In [2]:
arr_1D = np.arange(1,11)
arr_1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Indexing mit positiven Zahlen
Bei Angabe von positiven Zahlen, startet der Index vom Anfang des Arrays mit 0 und zählt hoch in Richtung Ende des Arrays.
<br>
Beispiel: 4.tes Element 

In [3]:
arr_1D[3]

np.int64(4)

#### Indexing mit negativen Zahlen
Bei Angabe von negativen Zahlem, startet der Index vom Ende des Arrays mit -1 und zählt runter (-2,-3,...) in Richtung Anfang des Arrays.
Beispiel: vorletztes Element

In [4]:
arr_1D[-2]

np.int64(9)

#### Slicing
Start:Stop:Step
<br> 
Der Step is optional; default ist 1.
<br>
Start und Stop können weggelassen werden, wenn Anfang oder Ende des Arrays gemeint sind.
<br>
Beispiel: Angefangen vom 2.ten Element (Index 1) bis zum 6.ten Element (Index 5) jedes zweite Element ausgeben.

In [5]:
arr_1D[1:6:2]

array([2, 4, 6])

Beispiel: alle Elemente ausgeben

In [6]:
arr_1D[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Beispiel: alle Element in umgekehrter Reihenfolge ausgeben:

In [7]:
arr_1D[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

Beispiel: vom zweiten Element (Index 1) bis zum Ende des Arrays die Element ausgeben:

In [8]:
arr_1D[1:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Maske

Beispiel: Ausgabe aller Elemente, die größer als 5 sind

In [9]:
mask = arr_1D>5
mask

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [10]:
arr_1D[mask]

array([ 6,  7,  8,  9, 10])

### Zwei-dimensionales Array

In [11]:
arr_2D = np.array([[  1,  2,  3,  4],
                   [  5,  6,  7,  8],
                   [  9, 10, 11, 12],
                   [ 13, 14, 15, 16],
                   [ 17, 18, 19, 20],])

#### Indexing
Beispiel: Element zweite Zeile (Index 1) und dritte Spalte (Index 2)

In [12]:
arr_2D[1,2]

np.int64(7)

In [13]:
arr_2D[-4,-2]

np.int64(7)

#### Slicing

Beispiel: gesamte zweite Zeile zurückgeben

In [14]:
arr_2D[1]

array([5, 6, 7, 8])

In [15]:
arr_2D[1,:]

array([5, 6, 7, 8])

Beispiel: gesamte dritte Spalte zurückgeben

In [16]:
arr_2D[:,2]

array([ 3,  7, 11, 15, 19])

Auswahl eines Bereichs
<br>
Beispiel: Bereich zweite bis fünfte Zeile und zweite bis vierte Spalte

In [17]:
arr_2D[1:5,1:4]

array([[ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16],
       [18, 19, 20]])

In diesem Beispiel kann die explizite Angabe der fünften Zeile entfallen, weil die auch das Ende der Zeilen des Arrays ist.

In [18]:
arr_2D[1:,1:4]

array([[ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16],
       [18, 19, 20]])

Schrittweite
<br>
Beispiel: Die gerade Zeilen der dritten Spalte

In [19]:
arr_2D[1::2,2]

array([ 7, 15])

Beispiel: Die ungeraden Zeilen der dritten Spalte

In [20]:
arr_2D[0::2,2]

array([ 3, 11, 19])

Die explizite Angabe der ersten Zeile entfallen, weil dies der Anfang des Arrays ist.

In [21]:
arr_2D[::2,2]

array([ 3, 11, 19])

#### Maske
Beispiel: Ausgabe aller Zahlen die zwischen 7 und 11 liegen

In [22]:
mask = (arr_2D>=7) & (arr_2D<=11)
mask

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True, False],
       [False, False, False, False],
       [False, False, False, False]])

In [23]:
arr_2D[mask]

array([ 7,  8,  9, 10, 11])