# Numpy - Übung 1

2026-05-03 ug - Version 1.1

In [ ]:
import numpy as np

**Aufgabe1:** Erzeuge folgendes 2D NumPy Array

![Bild 1](..\bilder\Numpy_Übung_1_Bild_1.png)

erwartetes Ergebnis:
```Python 
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])
```
Verwende `arange()` und `reshape()`
Speichere das Ergebnis in der Variablen `a`.
<br>
Bitte die Anweisung in folgende Zelle eintragen:

In [ ]:
# Bitte hier die Lösung eintragen

**Aufgabe2**: Erzeuge folgenden Ausschnitt:

![Bild 2](..\bilder\Numpy_Übung_1_Bild_2.png)

Erwartetes Ergebnis:
```Python 
np.int64(7)
```
Bitte die Anweisung in folgende Zelle eintragen:

In [ ]:
# Bitte hier die Lösung eintragen

**Aufgabe3**: Erzeuge folgenden Ausschnitt:

![Bild 3](..\bilder\Numpy_Übung_1_Bild_3.png)

Erwartetes Ergebnis:
```Python 
array([ 6,  7,  8,  9, 10, 11])
```
Bitte die Anweisung in folgende Zelle eintragen:

In [ ]:
# Bitte hier die Lösung eintragen

**Aufgabe4**: Erzeuge folgenden Ausschnitt:

![Bild 4](..\bilder\Numpy_Übung_1_Bild_4.png)

Erwartetes Ergebnis:
```Python 
array([ 2,  8, 14, 20, 26])
```
Bitte die Anweisung in folgende Zelle eintragen:

In [ ]:
# Bitte hier die Lösung eintragen

**Aufgabe5**: Erzeuge folgenden Ausschnitt:

![Bild 5](..\bilder\Numpy_Übung_1_Bild_5.png)

Erwartetes Ergebnis:
```Python 
array([[ 2,  5],
       [ 8, 11],
       [14, 17],
       [20, 23],
       [26, 29]])
```
Bitte die Anweisung in folgende Zelle eintragen:

In [ ]:
# Bitte hier die Lösung eintragen

**Aufgabe6**: Erzeuge folgenden Ausschnitt:

![Bild 6](..\bilder\Numpy_Übung_1_Bild_6.png)

Erwartetes Ergebnis:
```Python 
array([[ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17]])
```
Bitte die Anweisung in folgende Zelle eintragen:

In [ ]:
# Bitte hier die Lösung eintragen

**Aufgabe7**: Erzeuge folgenden Ausschnitt:

![Bild 7](..\bilder\Numpy_Übung_1_Bild_7.png)

Erwartetes Ergebnis:
```Python 
array([13, 14, 15, 16])
```
Bitte die Anweisung in folgende Zelle eintragen:

In [ ]:
# Bitte hier die Lösung eintragen

**Aufgabe8**: Erzeuge folgenden Ausschnitt:

![Bild 8](..\bilder\Numpy_Übung_1_Bild_8.png)

Erwartetes Ergebnis:
```Python 
array([[ 7,  9],
       [19, 21]])
```
Bitte die Anweisung in folgende Zelle eintragen:

In [ ]:
# Bitte hier die Lösung eintragen